Part14
vtpros/TestGuru pull request #13
Opened 2021-02-19 23:04 UTC by vtpros

1. Используйте официальный клиент GitHub Octokit
2. Выводите ссылку на созданный gist во flash сообщении
3. Добавьте интернационализацию в сервис GistQuestionService
4. Добавьте модель Gist. У администратора сделайте вывод таблицы всех созданных gist. Таблица должна содержать обязательные колонки:
     Вопрос. Отображаются первые 25 символов тела вопроса в виде ссылки. По клике на ссылку отображается страница вопроса (действие show)
     Gist URL. Отображается хэш созданного gist в виде ссылки
     Пользователь. Отображается email пользователя который создал gist

 5. Поместите токен в .env файл и используйте github.com для его загрузки в окружение приложения

2021-02-20 10:49 UTC, VidgarVii requested changes

2021-02-20 10:49 UTC, VidgarVii commented on Gemfile
> +gem 'faraday'
faraday я думаю тут вряд ли уже используется

2021-02-20 10:49 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  before_action :_test_passage, only: %i[show update result gist]
Gist как полноценная модель заслуживает иметь собственный контроллер. Надо придерживаться REST соглашению

2021-02-20 10:49 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  before_action :_test_passage, only: %i[show update result gist]
_ не к чему

2021-02-20 10:49 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    flash_options = if gist
еслиметод #call возращает объект Gist. то назовыи тогда метод соответствующи.

2021-02-20 10:49 UTC, VidgarVii commented on config/locales/en.yml
> +      success: "Gist successfully created: %{url}"
ссылка должна быть кликабельная. 
Юзер должен видеть только хэш гиста. Это _7eecf42f02e7b0421558498574032fa_

2021-02-20 12:41 UTC, vtpros commented on Gemfile
> +gem 'faraday'
Да, забыл убрать

2021-02-20 12:43 UTC, vtpros commented on Gemfile
> +gem 'faraday'
Вернее, он используется, но как зависимость Octokit

2021-02-20 17:34 UTC, vtpros commented on app/controllers/test_passages_controller.rb
> +  before_action :_test_passage, only: %i[show update result gist]
Не очень понял, что ты имеешь в виду. У gist есть собственный контроллер, он используется для вывода списка всех gist. Я как-то могу создать gist обращаясь из TestPassagesController к GistsConroller? Я могу прописать путь и соответствующий метод для `new`, но я не знаю, как в таком случае передать окружение (@test_passage) туда.

2021-02-20 19:01 UTC, VidgarVii commented on Gemfile
> +gem 'faraday'
при установке гема, все зависимости он ставим сам. Это можно посмотреть в Gemfile.lock

2021-02-20 19:03 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  before_action :_test_passage, only: %i[show update result gist]
тебе нужен только 1 экшен в GistsController это create. Все нужные данные передаешь параметрами

2021-02-20 19:08 UTC, VidgarVii requested changes

2021-02-20 19:08 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    new_gist = GistQuestionService.new(question, current_user).create_gist
тогда уж build_gist чтобы как то повторить соглашение рельсы. Единообразие

2021-02-20 19:08 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    gist_hash = url[url.rindex('/') + 1..-1]
url.split('/').last ?

а еще лучше этот хэш(ид) вытащить через response octokit.

2021-02-20 19:08 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    return nil unless result
а такое возможно?

2021-02-20 19:22 UTC, vtpros commented on Gemfile
> +gem 'faraday'
Это да.

2021-02-20 19:27 UTC, vtpros commented on app/services/gist_question_service.rb
> +    return nil unless result
В случае, если Octokit не смог создать gist, я передаю nil сюда и его же в контроллер для проверки успешности

2021-02-21 11:50 UTC, VidgarVii commented on .rubocop_todo.yml
>      - 'app/controllers/admin/base_controller.rb'
либо следуй рекомендациям рубокопа. Либо отключи эту опцию полностью

2021-02-21 11:50 UTC, VidgarVii commented on lib/clients/git_hub_client.rb
> +  rescue Octokit::Unauthorized
тут ты проверяешь только Octokit::Unauthorized. Сомнительное решение если честно. Лучше бы если ошибки были явные. Так сразу понятно куда копать без изучения кода. Мб банально токен быть не верным. Тогда и будет  Octokit::Unauthorized. Это важная и нужная ошибка. А ты этого не узнаешь. Еще причины по которой может не создаться гист могут быть разные. Я бы на начальном этапе поставил бы только 1 проверку. Это Создался ли гист. При этом octokit возвращает 201 статут

2021-02-21 11:50 UTC, VidgarVii commented on lib/clients/git_hub_client.rb
> +  ACCESS_TOKEN = ENV['GITHUB_ACCESS_TOKEN']
если GITHUB_ACCESS_TOKEN не будет. то ошибка будет на стороне октокит. Что не совсем корректно. Тем более ты эту ошибку зачем-то обрабатываешь. Лучше проверку токена делать явной. Для этого можно воспользоваться 
ENV.fetch('GITHUB_ACCESS_TOKEN')

2021-02-21 16:42 UTC, merged