Finish part8 tasks
vtpros/TestGuru pull request #7
Opened 2020-10-27 13:56 UTC by vtpros

1. Реализуйте все стандартные действия вместе с представлениями (видами) для ресурса вопросов:
Список вопросов теста должен выводиться на той же странице, что и сам тест
Используйте фрагменты представлений там, где это уместно
Для того чтобы метод form_with смог сформировать верный URL используйте вызов form_with model: [@parent, @child]
В представлениях должны быть ссылки для навигации между страницами приложения

2. Добавьте футер в котором будет выводиться текущий год, имя автора, название проекта (в виде ссылки на GitHub-репозиторий проекта), его краткое описание и ссылка с текстом "Учебный проект в онлайн-школе Thinknetica", ведущая на адрес thinknetica.com

3. Напишите хэлперы:
Для заголовка формы создания и редактирования вопроса. Это должен быть один метод question_header который в форме создания вопроса будет выводить Create New <Test Title> Question, а в форме редактирования Edit <Test Title> Question
Для вывода текущего года в футере
Для формирования ссылки на GitHub репозиторий: github_url(author, repo)

4. Добавьте в представление списка тестов количество вопросов для каждого теста

2020-10-27 18:52 UTC, VidgarVii requested changes

2020-10-27 18:52 UTC, VidgarVii commented on app/assets/stylesheets/tests.scss
> +// Place all the styles related to the tests controller here.
если подобные файлики остаются пустые то, удаляем =) Лучше их создавать вручную при необходимости.

2020-10-27 18:52 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    render html: "<h4>Question has been deleted</h4>".html_safe, status: :ok
контроллер ни когда не должен заниматься генерацией контента. Ни какого. Контроллер это всего лишь делегатор задачи. Для формирования html у нас есть Action View. Используй её. Возвращать клиенту ответ о выполненной операции конечно нужно. Для удаления хорошо подходит фораты json или js. Это вы будете проходить потом. На данном этапе достаточно будет redirect_to. так как в твоем ответе нет ссылки на предыдущую страницу

2020-10-27 18:52 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question.update(question_params) ? (render :show) : (render :edit)
это не тот случай когда надо использовать тернарники. 

надо будет тебе определить значение для переменной тогда ок.
var = condition ? value : defoult_value
или делегировать вызов другого метода в методе. В общем не наш случай. Ссылка на стайлгайд [экшенов](https://github.com/arbox/rails-style-guide/blob/master/README-ruRU.md#save-bang)
Кстати тут еще баг. Если вопрос не обновиться, то AR выкенет исключение, которая надо выводиться в браузере. У тебя при создании или обновлении вопросов ошибки на странице ни как не отображаются. Клиент всегда должен видеть, что он делает не так

2020-10-27 18:52 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>      question = @test.questions.create!(question_params)
используя bang! методы ты выбрасываешь исключение, которые надо всегда обрабатывать. В данном случаи клиент даже не поймет, почему вопрос не создался, если будет ошибка. Вообще строить бизнес логику на исключениях не очень хорошая идея. Так как ошибка выбрасывается ну ооочень долго. Используй классический вариант. 
if
else
end

2020-10-27 18:52 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    render html: helpers.tag.strong("Question doesn't exist"), status: :not_found
кстати элемент `<strong>` является семантическим. Указывает на важность контекста внутри определенного текста.  этот тег не используют для выделения текста жирным. Для стилей есть css. Хелперы так же следует использовать только внутри action view

Так же для хтмл должен быть отдельный partial
Можно сделать так. 
```
render 'shared/errors/record_not_found', status: :not_found
```
при этом создать директорию в app/views/shared/errors
внутри файл record_not_found.html.erb
а внутри уже можно реализовать свою фанатзию =)

2020-10-27 18:52 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @questions = @test.questions
лучше эту строчку закинуть в экшен show. Так точно мы будем понимать от куда берется переменная @test И тогда не надо будет волноваться над позиции строк 2 и 3. Если кто-то случайно поменяет их местами, то у тебя будет ошибка метод questions не определен для NilClass
А вообще по моему опыту скажу. Меньше колбеков безопасней код.  И читать проще

2020-10-27 18:52 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    Time.now.year
тут ошибка может случиться 31 декабря по 1 января =) Так как .now не учитывает временную зону. Всегда при работу со временем или датами используй current. Т.е.
`Time.current....`

2020-10-27 18:52 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    "https://github.com/#{author}/#{repo}/"
используй хелпер link_to
rails way =)
https://apidock.com/rails/ActionView/Helpers/UrlHelper/link_to

2020-10-27 18:52 UTC, VidgarVii commented on app/helpers/questions_helper.rb
> +  METHODS = {edit: 'Edit', create: 'Create New'}.freeze
1. слишком абстрактное имя. Или вообще какие методы? ООП?)  Имена переменных и констант должны говорить какую информацию они содержат. Да нейминг в программировании это самое сложное. 
2. перед/после { ... } должны быть отступы
`{ edit: 'Edit', create: 'Create New' }`

2020-10-27 18:52 UTC, VidgarVii commented on app/views/layouts/application.html.erb
> +    <footer>
было бы замечательно такие вещи в отдельных паршалах хранить.

остенеться только его подключить.
render 'shared/footer'

2020-10-27 18:52 UTC, VidgarVii commented on app/views/layouts/application.html.erb
> +      <a href="<%= github_url('vtpros', 'TestGuru') %>">Учебный проект</a>  в онлайн-школе
= link_to

https://apidock.com/rails/ActionView/Helpers/UrlHelper/link_to

2020-10-27 18:52 UTC, VidgarVii commented on app/views/questions/_question.html.erb
> +<li><%= link_to "#{question.body}", question_path(question) %></li>
можно без интерполяции
Просто `link_to question.body, question_path(question)`

2020-10-27 18:52 UTC, VidgarVii commented on app/views/questions/edit.html.erb
> +  <%= f.text_area(:'body') %><br>
поля для паршалов edit и new часто бывают идентичны. Можно их положить отдельно в паршал и подключать где надо

2020-10-27 18:52 UTC, VidgarVii commented on app/views/questions/index.html.erb
> +<h2>
так как по заданию мы список вопросов выводим на странице самого теста. Этот файл и экшен можно удалить

2020-10-27 18:52 UTC, VidgarVii commented on app/views/tests/index.html.erb
> +<h2>Tests:</h2>
семантически h2 нельзя ставить если нет h1

2020-10-27 18:52 UTC, VidgarVii commented on test/controllers/tests_controller_test.rb
> +require 'test_helper'
эти артефакты не будем использовать. Смело можно, даже нужно удалять.

2020-10-28 03:03 UTC, max-underthesun commented on app/controllers/questions_controller.rb
>    before_action :find_test, only: %i[index create new]
>ТЗ: "Список вопросов теста должен выводиться **на той же странице, что и сам тест**"

другими словами - в этом контроллере этот экшен не нужен, индекс вопросов конкретного теста должен выводиться на странице этого теста (TestsController #show и соответствующая вьюха) , как у тебя и сделано
здесь индекс лишний (не забудь убрать роут и поправить вызов коллбека)

2020-10-28 03:03 UTC, max-underthesun commented on app/controllers/tests_controller.rb
> +class TestsController < ApplicationController
скромный получился контроллер )
а где же остальные экшены?
повтори все что было в скринкасте
здесь нужен весь набор экшенов

2020-10-28 03:03 UTC, max-underthesun commented on app/views/questions/new.html.erb
> +<%= question_header(@test, :create) %>
вместо передачи из паршелов индикаторов, типа `:create` для определения создается ресурс или редактируется
лучше использовать хелперы `.persisted?` или `.new_record?`
передавай в метод объект вопроса и по его состоянию ориентируйся что происходит (редактирование или создание)

2020-10-28 03:03 UTC, max-underthesun commented on app/views/questions/new.html.erb
> +<%= question_header(@test, :create) %>
Павел уже написал про это, подтверждаю: правильно будет вынести форму в паршел из обеих вьюх ("нью" и "эдит")

2020-11-01 12:11 UTC, VidgarVii requested changes

2020-11-01 12:11 UTC, VidgarVii commented on app/controllers/tests_controller.rb
>    before_action :find_questions, only: :show
2 колбека ради 1 экшена. Если есть возможно не писать колбеки, то лучше их не использовать Всегда хочется видеть всю информацию которая используется в методе, а не гадать и не искать от куда же берутся данные

2020-11-01 12:11 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +<% @question = Question.new %>
такие вещи должны быть в контроллере. Только контроллер отвечает за передачу нужных данных в представление

2020-11-01 12:11 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +<%= render 'shared/question_form', model: [@test, @question] %>
не совсем понял посыл)
это оставляешь тут
```
= form_with(путь, local: true) do |f| 
```
а поля рендерешь через паршал. Так как они не меняются.

2020-11-01 12:11 UTC, VidgarVii commented on app/views/tests/edit.html.erb
> +<% if @test.errors.present? %>
хорошо бы эту логике засунуть 1 раз в shared/errors/errors_list и больше про неё ни где не вспоминать.

2020-11-01 12:11 UTC, VidgarVii commented on app/views/tests/new.html.erb
> +<% @test = Test.new %>
это надо убрать в контроллер.  Почему писал выше
Еще тогда при ошибки валидации, не придется пере заполнять все поля, так как объект сохранен в памяти

2020-11-01 12:11 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    if @test.destroy
по логике методо destroy и редиректа более чем достаточно

2020-11-01 12:33 UTC, vtpros commented on app/controllers/tests_controller.rb
>    before_action :find_questions, only: :show
Это при второй подаче уже было исправлено
@questions = @test.questions перенёс в show
в колбэк добавил остальные экшены

2020-11-01 12:43 UTC, vtpros commented on app/views/questions/new.html.erb
> +<%= render 'shared/question_form', model: [@test, @question] %>
Из задания: Для того чтобы метод form_with смог сформировать верный URL используйте вызов `form_with model: [@parent, @child]`
Используется одна форма для `:new` и `:edit`, а `model:` в них отличается. Передаю нужную модель через параметры.

2020-11-01 14:51 UTC, merged