Part10
vtpros/TestGuru pull request #9
Opened 2020-12-15 07:35 UTC by vtpros

1. Добавьте в сессию идентификатор пользователя после его регистрации
2. Создайте хэлпер для flash сообщений
3. Реализуйте выход пользователя из системы
4. Создайте навигацию с названием проекта и ссылками для регистрации/логина/выхода пользователя. Если пользователь находится в системе - выводить сообщение Welcome, <user name> Guru. Название проекта должно быть ссылкой и вести на главную страницу приложения.
5. Разрешите действия над остальными ресурсами только для пользователя который вошел в систему
6. С помощью механизма куки реализуйте перенаправление пользователя после логина на ту страницу куда он хотел попасть изначально
7. Проверяйте формат и уникальность атрибута email для пользователя
8. Используйте объект текущего пользователя при старте прохождения теста

2020-12-15 16:25 UTC, VidgarVii requested changes

2020-12-15 16:25 UTC, VidgarVii commented on app/controllers/users_controller.rb
> +    @user = User.new(user_params)
Инстанс-переменнуя тут не будет использоваться. Достаточно локальной

2020-12-15 16:25 UTC, VidgarVii commented on app/controllers/users_controller.rb
> +    end
возьми за практику такую вещь. Если конструкция получается 
```
if
elsif
else
end
```
То значит это не верное решение

2020-12-15 16:25 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    tag.p flash[:alert], class: 'flash alert' if flash[:alert]
1 Тип флеша нужно передавать параметром. От этого типа так же зависит CSS класс, чтобы разные флеши отображались по-разному
2 ключи у флеша могут быть разные, не обязательно `:alert`

2020-12-15 16:25 UTC, VidgarVii commented on config/routes.rb
> +  get :logout, to: 'sessions#logout'
1 соблюдай конвенции REST: удаление ресурса (сессии) логично делать через DELETE, а не через GET
2 в контроллере правильно использовать экшен `#destroy` для удаления объекта (сессии)

2020-12-15 16:25 UTC, VidgarVii commented on app/controllers/concerns/authenticatible.rb
> +module Authenticatible
сразу скажу. модуль на удаление. 
очень не явно.
лишняя связь и сложность
оверхед
не явный редирект можно профокапить и в контроллере словить двойной редирект.
миксины в контроллерах не так делаются. Нужно использовать консерны

2020-12-15 16:25 UTC, VidgarVii commented on app/controllers/users_controller.rb
> +    end
после созданию юзера надо сделать запись в сессию и отправить юзера на нужную страницу и всё

2020-12-15 16:25 UTC, VidgarVii commented on app/controllers/concerns/authenticatible.rb
> +      redirect_to session[:URI] || root_path
хорошо бы session[:URI] сразу удалять, во избежании багов с неудачными возвратами.

2020-12-15 16:25 UTC, VidgarVii commented on app/views/layouts/application.html.erb
> +      <div class="nav user">Welcome, <%= @current_user.email %> Guru</div>
1 у тебя уже есть хeлпер метод current_user
2 Обычно приветствуют по имени, а не по почте)

2020-12-15 16:25 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!
лучше не в ApplicationController запускать authenticate_user!, а явно в тех контроллерах где это требуется. Мб это показаться дублированием. Но за то не будут лишних сюрпризов

2020-12-15 16:25 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +    session[:user_id] = nil
хранить ключ с нилом оверхед. удаляй данные полностью
```
session.delete(:user_id)
```

2020-12-15 16:25 UTC, VidgarVii commented on app/controllers/users_controller.rb
> +
всё что ниже на удаление. Смотри еще раз урок про валидацию форм и моделей

2020-12-15 16:25 UTC, VidgarVii commented on app/models/user.rb
> +  has_secure_password
has_secure_password валидирует только пароль.
Причина удаления валидации не ясна

2020-12-15 16:25 UTC, VidgarVii commented on app/models/user.rb
> +  has_secure_password
нет валидации почты

2020-12-16 07:30 UTC, vtpros commented on app/controllers/users_controller.rb
> +    @user = User.new(user_params)
`@user` используется в паршиал форме создания пользователя для вывода ошибок
```ruby
<%= render 'shared/errors/errors_list', resource: @user %>
```
Если убрать строку, тогда не выводится сообщение о несовпадении паролей. Но попробую переместить ошибки во `flash`

2020-12-16 07:50 UTC, vtpros commented on app/controllers/users_controller.rb
> +    @user = User.new(user_params)
Также она используется в той же форме в
```ruby
<%= form_with model: @user, local: true do |f| %> 
```
Если сохранение не удалось (пароль пустой или не совпадает), контроллер рендерит форму `new`, но модель теперь указавает на `nil` и `params.require(:user)` получается пустой. Получается перед рендерингом формы нужно заново создавать нового пользователя через `@user = User.new`. Но таким образом теряется заполнение полей и пользователю нужно заново заполнять имя и емэйл.

Каким образом это можно исправить без инстанс-переменной?

2020-12-16 20:08 UTC, VidgarVii requested changes

2020-12-16 20:08 UTC, VidgarVii commented on app/controllers/answers_controller.rb
> +  end
советую кешировать данные. 
@answer ||=
@question ||=
бывают проблемы, либо лишние запросы идут, либо ошибки не приходят при обновлении объекта

2020-12-16 20:08 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +  helper_method :current_user,
если helper_method относится к приват методам. Лучше helper_method объявлять после private

2020-12-16 20:08 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      session.delete(:URI)
session.delete(:URI) вернет session[:URI]. используй

2020-12-16 20:08 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    if @test.questions.blank? || @test.questions.any? { |q| q.answers.blank? }
а вот такой ситуации вообще надо избегать. такие тесты не должны быть опубликованы в открытом доступе. Публикацию тестов мы не будем реализовывать. Так что просто держи данные в порядке

2020-12-16 20:08 UTC, VidgarVii commented on app/controllers/users_controller.rb
> +      session.delete(:URI)
отписал выше про session.delete(:URI).
в контроллерах код типо redirect_to и render должны стоять последними

2020-12-16 20:08 UTC, VidgarVii commented on app/models/test.rb
> +        lambda { |name|
по стайл гайду если скоуп занимает больше 1 строчки. То принято выносить это в метод класса https://github.com/rubocop-hq/rails-style-guide#named-scope-class

2020-12-16 20:08 UTC, VidgarVii commented on app/models/user.rb
> +  validates :email, format: { with: /@/ },
одно наличие @ еще не гарантия что приходит почта.
используй URI::MailTo::EMAIL_REGEXP

2020-12-16 20:55 UTC, vtpros commented on app/controllers/tests_controller.rb
> +    if @test.questions.blank? || @test.questions.any? { |q| q.answers.blank? }
Ну я создаю тест, но ещё не успел его доделать. Но кнопка "Start" у меня на него уже есть. Мне кажется лучше лишняя проверка, чем неясная ошибка при попытке его начать. Либо где-то проверку на возможность вызова "Start" ещё реализовывать.

2020-12-16 21:04 UTC, vtpros commented on app/models/user.rb
> +  validates :email, format: { with: /@/ },
Это я по мотивам статьи: https://habr.com/ru/post/175375/

2020-12-16 21:17 UTC, vtpros commented on app/controllers/tests_controller.rb
> +    if @test.questions.blank? || @test.questions.any? { |q| q.answers.blank? }
А, вынес проверку в `before_action`

2020-12-17 08:12 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +  def _test
_ в названиях метода не используется

2020-12-17 08:32 UTC, vtpros commented on app/controllers/questions_controller.rb
> +  def _test
Рубокоп [советует](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Naming/MemoizedInstanceVariableName) так.
Как вариант назвать `:test` , но не возникнет ли потом конфликтов с локальными переменными?
Либо переименовывать инстанс-переменную и заменять везде.

2020-12-17 11:51 UTC, merged